"""
Tests for the pinned dependency lock files (DEP-6a).

requirements.lock (runtime) and requirements-dev.lock (runtime + dev
extra) are generated by `uv pip compile` for the production target
(Python 3.12, Linux x86_64). These tests are pure unit checks — they
parse the files and pyproject.toml, no database needed:

- every non-comment line is an exact ``name==version`` pin;
- every direct dependency declared in pyproject.toml appears in the
  matching lock;
- the runtime lock is a subset of the dev lock;
- the packages whose drift already broke us once are pinned.
"""

from __future__ import annotations

import re
import tomllib
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parent.parent
RUNTIME_LOCK = BACKEND_DIR / "requirements.lock"
DEV_LOCK = BACKEND_DIR / "requirements-dev.lock"
PYPROJECT = BACKEND_DIR / "pyproject.toml"

PIN_RE = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s]+)$")
REQ_NAME_RE = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)")

CRITICAL_PACKAGES = {
    "sqlalchemy",
    "asyncpg",
    "psycopg2-binary",
    "alembic",
    "fastapi",
    "uvicorn",
    "pydantic",
    "pyjwt",
}


def _norm(name: str) -> str:
    """PEP 503 normalisation: case- and separator-insensitive."""
    return re.sub(r"[-_.]+", "-", name).lower()


def _parse_lock(path: Path) -> dict[str, str]:
    """Return {normalised_name: version}; assert strict pin format."""
    pins: dict[str, str] = {}
    for lineno, raw in enumerate(path.read_text().splitlines(), start=1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        match = PIN_RE.match(line)
        assert match, f"{path.name}:{lineno} is not an exact pin: {raw!r}"
        assert "," not in match.group(2), f"{path.name}:{lineno} compound specifier: {raw!r}"
        pins[_norm(match.group(1))] = match.group(2)
    return pins


def _direct_names(pyproject: dict, section: list[str]) -> set[str]:
    return {_norm(REQ_NAME_RE.match(req).group(1)) for req in section}


def _pyproject() -> dict:
    return tomllib.loads(PYPROJECT.read_text())


def test_lock_files_exist() -> None:
    assert RUNTIME_LOCK.is_file(), "requirements.lock missing — regenerate with uv pip compile"
    assert DEV_LOCK.is_file(), "requirements-dev.lock missing — regenerate with uv pip compile"


def test_every_line_is_exact_pin() -> None:
    for lock in (RUNTIME_LOCK, DEV_LOCK):
        pins = _parse_lock(lock)
        assert pins, f"{lock.name} contains no pins"


def test_runtime_direct_dependencies_pinned() -> None:
    project = _pyproject()["project"]
    declared = _direct_names(project, project["dependencies"])
    locked = _parse_lock(RUNTIME_LOCK)
    missing = declared - set(locked)
    assert not missing, f"declared in pyproject but missing from requirements.lock: {sorted(missing)}"


def test_dev_direct_dependencies_pinned() -> None:
    project = _pyproject()["project"]
    declared = _direct_names(project, project["optional-dependencies"]["dev"])
    locked = _parse_lock(DEV_LOCK)
    missing = declared - set(locked)
    assert not missing, f"declared in pyproject dev extra but missing from requirements-dev.lock: {sorted(missing)}"


def test_runtime_lock_subset_of_dev_lock() -> None:
    runtime = _parse_lock(RUNTIME_LOCK)
    dev = _parse_lock(DEV_LOCK)
    missing = sorted(set(runtime) - set(dev))
    assert not missing, f"in requirements.lock but not requirements-dev.lock: {missing}"
    drifted = sorted(n for n in runtime if n in dev and dev[n] != runtime[n])
    assert not drifted, (
        "same package pinned to different versions in the two locks "
        f"(regenerate both in one commit): {drifted}"
    )


def test_critical_packages_pinned() -> None:
    for lock in (RUNTIME_LOCK, DEV_LOCK):
        locked = _parse_lock(lock)
        missing = CRITICAL_PACKAGES - set(locked)
        assert not missing, f"critical packages missing from {lock.name}: {sorted(missing)}"
