"""
Fix tick_log schema: drop UNIQUE on turn_number, add PK/autoincrement on id.

Two repairs, both required for tick_log to serve its purpose:

1. turn_number UNIQUE -> indexed only. Multiple rows may share a
   turn_number (each scheduled retry after a failed tick is its own
   attempt); the latest row by id is the authoritative one. The
   separate ix_tick_log_turn_number index is kept.

2. id BIGINT NOT NULL -> INTEGER PRIMARY KEY with real autoincrement.
   Migration 0001 declared autoincrement=True but never a primary_key,
   so migrated databases got a plain NOT NULL column with no sequence:
   every tick_log insert raised NOT NULL violations on Postgres (and on
   migrated SQLite). Only metadata create_all (tests) ever worked.

Uses op.batch_alter_table: SQLite cannot drop constraints in place and
must rebuild the table. The turn_number unique was declared inline
without a name, so on SQLite it is reflected unnamed — a uq naming
convention is supplied so the reflected constraint becomes addressable
as uq_tick_log_turn_number. On Postgres the constraint is resolved via
inspection (dialect default tick_log_turn_number_key) and the id column
gets GENERATED BY DEFAULT AS IDENTITY, which batch_alter_table cannot
emit.
"""

from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: tuple[str, ...] | None = None
depends_on: tuple[str, ...] | None = None

_UQ_NAMING = {"uq": "uq_%(table_name)s_%(column_0_name)s"}
_UQ_TURN_NUMBER = "uq_tick_log_turn_number"


def _turn_number_unique_name() -> str | None:
    """Resolve the unique constraint's real name, or the convention name."""
    inspector = sa.inspect(op.get_bind())
    for uq in inspector.get_unique_constraints("tick_log"):
        if uq.get("column_names") == ["turn_number"]:
            return uq.get("name") or _UQ_TURN_NUMBER
    return None


def upgrade() -> None:
    bind = op.get_bind()
    constraint_name = _turn_number_unique_name()

    with op.batch_alter_table(
        "tick_log", naming_convention=_UQ_NAMING
    ) as batch_op:
        if constraint_name is not None:
            batch_op.drop_constraint(constraint_name, type_="unique")
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger(),
            type_=sa.Integer(),
            nullable=False,
        )
        batch_op.create_primary_key("pk_tick_log", ["id"])

    if bind.dialect.name == "postgresql":
        # Identity sequence for future inserts; start above existing ids.
        next_id = bind.execute(
            sa.text("SELECT COALESCE(MAX(id), 0) + 1 FROM tick_log")
        ).scalar_one()
        op.execute(
            "ALTER TABLE tick_log ALTER COLUMN id "
            f"ADD GENERATED BY DEFAULT AS IDENTITY (START WITH {next_id})"
        )


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute(
            "ALTER TABLE tick_log ALTER COLUMN id DROP IDENTITY IF EXISTS"
        )

    with op.batch_alter_table("tick_log") as batch_op:
        batch_op.create_unique_constraint(_UQ_TURN_NUMBER, ["turn_number"])
        batch_op.alter_column(
            "id",
            existing_type=sa.Integer(),
            type_=sa.BigInteger(),
            nullable=False,
        )
        batch_op.drop_constraint("pk_tick_log", type_="primary")
